[package]
name = "tuner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
byteorder = "1.5.0"
cpal = "0.15.3"
imgui = "0.12.0"
imgui-glow-renderer = "0.13.0"
imgui-sdl2-support = "0.13.0"
num-complex = "0.4.6"
sdl2 = "0.37.0"
[profile.test]
inherits = "release"